//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarteGlobale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CarteGlobale()
        {
            this.CarteGroupes = new HashSet<CarteGroupe>();
        }
    
        public int idCarteGlobale { get; set; }
        public int idTypeRepas { get; set; }
        public string Element { get; set; }
    
        public virtual TypeRepa TypeRepa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarteGroupe> CarteGroupes { get; set; }
    }
}
