//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarteGroupe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CarteGroupe()
        {
            this.CarteRestaurants = new HashSet<CarteRestaurant>();
        }
    
        public int idCarteGroupe { get; set; }
        public int idGroupe { get; set; }
        public int idCarte { get; set; }
        public int PrixMinimum { get; set; }
    
        public virtual CarteGlobale CarteGlobale { get; set; }
        public virtual Groupe Groupe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarteRestaurant> CarteRestaurants { get; set; }
    }
}
