//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailReservation
    {
        public int idDetailReservation { get; set; }
        public int idReservation { get; set; }
        public string prenom { get; set; }
        public int entree { get; set; }
        public int plat { get; set; }
        public int dessert { get; set; }
        public int prixParPersonne { get; set; }
        public Nullable<int> idMenu { get; set; }
    
        public virtual Reservation Reservation { get; set; }
        public virtual DetailMenu DetailMenu { get; set; }
        public virtual Menu Menu { get; set; }
    }
}
